In [128]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [129]:
data=pd.read_csv('email_classification.csv')
data

email label
0    Upgrade to our premium plan for exclusive acce...   ham
1    Happy holidays from our team! Wishing you joy ...   ham
2    We're hiring! Check out our career opportuniti...   ham
3    Your Amazon account has been locked. Click her...  spam
4    Your opinion matters! Take our survey and help...   ham
..                                                 ...   ...
174  We're pleased to inform you that your refund h...   ham
175  Get rich quick! Invest in our revolutionary ne...  spam
176  Your free trial period is ending soon. Upgrade...   ham
177  Your order is on its way! Track your shipment ...   ham
178  Limited-time offer! Get 50% off on all purchas...  spam

[179 rows x 2 columns]

In [130]:
corpus=[]
for i in range(179):
    corpus.append(data.iloc[i,0])
print(corpus)

['Upgrade to our premium plan for exclusive access to premium content and features.', 'Happy holidays from our team! Wishing you joy and prosperity this season.', "We're hiring! Check out our career opportunities and join our dynamic team.", 'Your Amazon account has been locked. Click here to verify your account information.', 'Your opinion matters! Take our survey and help us enhance your experience.', 'Your payment has been received. Thank you for your prompt transaction.', 'Your email account storage is full. Click here to upgrade your account.', "Dear [Name], thank you for subscribing to our newsletter. Here's your welcome gift!", 'Your account has been credited with loyalty points. Redeem them for exciting rewards!', "You've been chosen for a free iPhone. Click here to claim your prize!", "Don't miss out on our special offer! Sign up now and get a discount on your first purchase.", "We're hiring interns for the summer. Apply now and gain valuable experience.", "You're pre-approved

### So corpus is our list of sentences which we need to convert into numerical data but after removing stopwords and lemmatizing each word from each sentence

In [131]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
Lemmatizer=WordNetLemmatizer()

In [132]:
print(set(stopwords.words('english')))

{'been', 'then', 'be', 'same', 'aren', "haven't", 'needn', "you've", 'had', 'which', 'while', 're', 'because', 'in', 'below', 'other', "didn't", "doesn't", 'won', 'why', 'my', 'do', 'has', 'themselves', 'them', 'myself', 'hasn', 'wasn', 'yours', 'now', 'if', 'this', 'into', 'o', "shan't", "isn't", 'just', "aren't", 'did', 'who', "won't", 'wouldn', "you'll", 'on', 'when', 'by', 'doing', "it's", 'but', 'didn', 'more', "don't", 'having', 'at', 'what', 'you', 'am', 'any', 'it', 't', 'have', 'above', 'yourself', 'does', 'and', 'its', 'me', 'himself', "you'd", 'these', 'through', 'are', 'before', 'after', 'such', "hadn't", 'between', 'couldn', 'hadn', 'some', 's', 'will', 'not', 'here', 'each', 'doesn', 'itself', 'shan', 'until', 'again', 'all', 'll', 'm', "needn't", 'to', 'isn', 'ours', 'or', 'during', 'both', "you're", 'ain', 'herself', "mightn't", 'as', 'nor', 'should', "should've", 'your', "shouldn't", 'a', 'don', 'i', 'against', "mustn't", 'shouldn', 'off', 'whom', 'for', 'those', 'of',

In [133]:
documents=[]
for sentence in corpus:
    words=sentence.split()
    words=[Lemmatizer.lemmatize(word) for word in words if word not in set(stopwords.words('english'))]
    sentence=" ".join(words)
    documents.append(sentence)
print(documents)

['Upgrade premium plan exclusive access premium content features.', 'Happy holiday team! Wishing joy prosperity season.', "We're hiring! Check career opportunity join dynamic team.", 'Your Amazon account locked. Click verify account information.', 'Your opinion matters! Take survey help u enhance experience.', 'Your payment received. Thank prompt transaction.', 'Your email account storage full. Click upgrade account.', "Dear [Name], thank subscribing newsletter. Here's welcome gift!", 'Your account credited loyalty points. Redeem exciting rewards!', "You've chosen free iPhone. Click claim prize!", "Don't miss special offer! Sign get discount first purchase.", "We're hiring intern summer. Apply gain valuable experience.", "You're pre-approved loan. Click apply now!", "We're thrilled introduce new collection. Shop enjoy exclusive discounts!", "We're excited announce upcoming webinar series. Register reserve spot!", "We've added new feature app based feedback. Update now!", "You're winner

In [134]:
X=documents
y=data[['label']]
y['label']=y['label'].map({'ham':1,'spam':0})

C:\Users\mahap\AppData\Local\Temp\ipykernel_21892\1466462653.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y['label']=y['label'].map({'ham':1,'spam':0})


In [135]:
y

label
0        1
1        1
2        1
3        0
4        1
..     ...
174      1
175      0
176      1
177      1
178      0

[179 rows x 1 columns]

In [136]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [137]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

### For most models, TF-IDF is enough as it converts the text into a suitable numerical form.

In [138]:
X_train

["We're experiencing technical difficulties. Our team working resolve issue ASAP.",
 'Your account banned. Click appeal ban.',
 "You're pre-approved loan. Click apply now!",
 "You've selected free trial premium service. Click activate now!",
 "We appreciate business. Here's token appreciation.",
 'URGENT: Your account compromised. Click reset password immediately.',
 'Your account upgraded VIP status. Enjoy enhanced benefit privileges.',
 'Your opinion matters! Take survey get chance win exciting prizes.',
 "We're hiring! Check career page current job openings.",
 'Your account flagged suspicious activity. Click verify identity.',
 "We've detected unusual activity account. Secure changing password.",
 "Don't miss end-of-season sale! Grab favorite item discounted prices.",
 "We're hosting live Q&A session tomorrow. Submit question advance!",
 "We're hiring! Check career opportunity join dynamic team.",
 "Congratulations! You've selected free trial premium software. Click download now!",

In [139]:
# def prediction_model(vectorizer):
#     vectorizer=vectorizer(max_features=2500,ngram_range=(1,2))
#     X_train=vectorizer.fit_transform(X_train).toarray()
#     X_test=vectorizer.transform(X_test).toarray()



In [140]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer

In [141]:
cv=CountVectorizer(max_features=2500,ngram_range=(1,2))
X_train=cv.fit_transform(X_train).toarray()
X_train


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 1]], dtype=int64)

In [142]:
X_test=cv.transform(X_test).toarray()

In [143]:
model=MultinomialNB()
model.fit(X_train,y_train)
y_pred=model.predict(X_test)

c:\Users\mahap\OneDrive\Desktop\C++,JS python codes\.vscode\ML-DL-NLP\myenv\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [144]:
y_pred

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0], dtype=int64)

In [145]:
print(f"The accuracy score for the Bag of Words embedding technique will be {accuracy_score(y_test,y_pred)}")
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

The accuracy score for the Bag of Words embedding technique will be 1.0
[[22  0]
 [ 0 14]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        22
           1       1.00      1.00      1.00        14

    accuracy                           1.00        36
   macro avg       1.00      1.00      1.00        36
weighted avg       1.00      1.00      1.00        36



In [146]:
tfidf=TfidfVectorizer(max_features=2500,ngram_range=(1,2))
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
X_train

["We're experiencing technical difficulties. Our team working resolve issue ASAP.",
 'Your account banned. Click appeal ban.',
 "You're pre-approved loan. Click apply now!",
 "You've selected free trial premium service. Click activate now!",
 "We appreciate business. Here's token appreciation.",
 'URGENT: Your account compromised. Click reset password immediately.',
 'Your account upgraded VIP status. Enjoy enhanced benefit privileges.',
 'Your opinion matters! Take survey get chance win exciting prizes.',
 "We're hiring! Check career page current job openings.",
 'Your account flagged suspicious activity. Click verify identity.',
 "We've detected unusual activity account. Secure changing password.",
 "Don't miss end-of-season sale! Grab favorite item discounted prices.",
 "We're hosting live Q&A session tomorrow. Submit question advance!",
 "We're hiring! Check career opportunity join dynamic team.",
 "Congratulations! You've selected free trial premium software. Click download now!",

In [147]:
X_train=tfidf.fit_transform(X_train).toarray()
X_test=tfidf.transform(X_test)

In [148]:
model.fit(X_train,y_train)
y_pred=model.predict(X_test)
y_pred

c:\Users\mahap\OneDrive\Desktop\C++,JS python codes\.vscode\ML-DL-NLP\myenv\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0], dtype=int64)

In [149]:
print(f"The accuracy score for the TF-IDF embedding technique will be {accuracy_score(y_test,y_pred)}")
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

The accuracy score for the TF-IDF embedding technique will be 1.0
[[22  0]
 [ 0 14]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        22
           1       1.00      1.00      1.00        14

    accuracy                           1.00        36
   macro avg       1.00      1.00      1.00        36
weighted avg       1.00      1.00      1.00        36

